apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-app
  template:
    metadata:
      labels:
        app: cpu-app
    spec:
      containers:
        - name: cpu-app
          image: 100xdevs/week-28:latest
          ports:
            - containerPort: 3000
          resources:
            requests: # This line was modified to match the metrics-server deployment
              cpu: '100m' # Adjusted to match the metrics-server request value 100m/1000 => 0.1 minumum
            limits:
              cpu: '300m'